# .kodiak.toml
version = 1

[merge]
automerge_label = "pr: automerge"
require_automerge_label = true
blocking_labels = ["status: pending", "status: in-progress", "status: dependent"]
method = "merge"
delete_branch_on_merge = true
optimistic_updates = false
prioritize_ready_to_merge = true

[merge.message]
title = "github_default"
body = "github_default"
include_coauthors= true
include_pr_number = true

body_type = "markdown"
strip_html_comments = true
