nodeLinker: pnp

packageExtensions:
  '@walletconnect/browser-utils@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/client@*':
    peerDependencies:
      '@walletconnect/encoding': '*'
      tslib: '*'
  '@walletconnect/core@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/http-connection@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/iso-crypto@*':
    peerDependencies:
      '@walletconnect/encoding': '*'
      tslib: '*'
  '@walletconnect/jsonrpc-types@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/jsonrpc-utils@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/qrcode-modal@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/socket-transport@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/utils@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/web3-provider@*':
    peerDependencies:
      '@walletconnect/encoding': '*'
      tslib: '*'
  env-cmd@*:
    peerDependencies:
      cross-spawn: '*'
  osmojs@*:
    dependencies:
      '@cosmjs/encoding': '*'
  recharts@*:
    peerDependencies:
      prop-types: '*'

yarnPath: .yarn/releases/yarn-3.2.4.cjs
