nodeLinker: pnp
pnpMode: loose

packageExtensions:
  '@walletconnect/browser-utils@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/client@*':
    peerDependencies:
      '@walletconnect/encoding': '*'
      tslib: '*'
  '@walletconnect/core@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/http-connection@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/iso-crypto@*':
    peerDependencies:
      '@walletconnect/encoding': '*'
      tslib: '*'
  '@walletconnect/jsonrpc-types@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/jsonrpc-utils@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/qrcode-modal@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/socket-transport@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/utils@*':
    peerDependencies:
      tslib: '*'
  '@walletconnect/web3-provider@*':
    peerDependencies:
      '@walletconnect/encoding': '*'
      '@babel/core': '*'
      tslib: '*'
  web3modal@*:
    peerDependencies:
      react-is: '*'
  multiaddr@*:
    peerDependencies:
      node-fetch: '*'
  dns-over-http-resolver@*:
    peerDependencies:
      node-fetch: '*'
  eth-block-tracker@*:
    peerDependencies:
      '@babel/core': '*'
  web3-provider-engine@*:
    peerDependencies:
      '@babel/core': '*'
  env-cmd@*:
    peerDependencies:
      cross-spawn: '*'
  osmojs@*:
    dependencies:
      '@cosmjs/encoding': '*'
  ipfs-core-types@*:
    peerDependencies:
      node-fetch: '*'
  ipfs-core-utils@*:
    peerDependencies:
      node-fetch: '*'
  ipfs-http-client@*:
    peerDependencies:
      node-fetch: '*'
  multiaddr-to-uri@*:
    peerDependencies:
      node-fetch: '*'
  caver-js@*:
    peerDependencies:
      node-fetch: '*'
yarnPath: .yarn/releases/yarn-3.2.4.cjs
