nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  # https://github.com/WalletConnect/walletconnect-monorepo/pull/1049
  '@walletconnect/iso-crypto@*':
    peerDependencies:
      '@walletconnect/encoding': '*'
  '@walletconnect/client@*':
    peerDependencies:
      '@walletconnect/encoding': '*'
  '@walletconnect/web3-provider@*':
    peerDependencies:
      '@walletconnect/encoding': '*'
