nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  # styled-components
  'styled-components@*':
    peerDependencies:
      'tslib': '*'

  # WalletConnect
  '@walletconnect/core@*':
    peerDependencies:
      'tslib': '*'
  '@walletconnect/utils@*':
    peerDependencies:
      'tslib': '*'
  '@walletconnect/http-connection@*':
    peerDependencies:
      'tslib': '*'
  '@walletconnect/socket-transport@*':
    peerDependencies:
      'tslib': '*'
  '@walletconnect/jsonrpc-utils@*':
    peerDependencies:
      'tslib': '*'
  '@walletconnect/jsonrpc-types@*':
    peerDependencies:
      'tslib': '*'
  '@walletconnect/iso-crypto@*':
    peerDependencies:
      '@walletconnect/encoding': '*'
      'tslib': '*'
  '@walletconnect/browser-utils@*':
    peerDependencies:
      'tslib': '*'
  '@walletconnect/qrcode-modal@*':
    peerDependencies:
      'tslib': '*'
  '@walletconnect/client@*':
    peerDependencies:
      '@walletconnect/encoding': '*'
      'tslib': '*'
  '@walletconnect/web3-provider@*':
    peerDependencies:
      '@walletconnect/encoding': '*'
      'tslib': '*'
